export type User = {
  id: number;
  uuid: string;
  photo: string;
  name: string;
  email: string;
  age: number;
  gender_origin: number;
  birth_date: string;
  phone_number: string;
  address: string;
  detail_address: string;
  last_login: string;
  created_at: string;
  updated_at: string;
  allow_marketing_push: boolean;
  is_active: boolean;
  is_staff: boolean;
  account_count: number;
};
